apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pollisense
type: Opaque
stringData:
  POSTGRES_DB: pollisense
  POSTGRES_USER: pollisense
  POSTGRES_PASSWORD: pollisense
---
apiVersion: v1
kind: Secret
metadata:
  name: ingestion-secret
  namespace: pollisense
type: Opaque
stringData:
  INGESTION_TOKEN: local-demo-token
